function confirm(){
	if(document.getElementById("mctext").value>3189346){
		document.getElementById("finalanswer").innerHTML="大於0";}
	else{
		if(document.getElementById("yctext").value>2484358){
			if(document.getElementById("yctext").value>2742268){
				document.getElementById("finalanswer").innerHTML="小於0";}
			else{
				if(document.getElementById("mctext").value>2702340){
					document.getElementById("finalanswer").innerHTML="大於0";}
				else{
					document.getElementById("finalanswer").innerHTML="小於0";}
			}
		}
		else{
			if(document.getElementById("mctext").value<=231330){
				if(document.getElementById("codetext").value<=3266){
					document.getElementById("finalanswer").innerHTML="小於0";}
				else{
					document.getElementById("finalanswer").innerHTML="大於0";}
			}
			else{
				if(document.getElementById("mctext").value>2213686){
					document.getElementById("finalanswer").innerHTML="大於0";}
				else{
					if(document.getElementById("yctext").value>1863723){
						if(document.getElementById("mctext").value>2033318){
							document.getElementById("finalanswer").innerHTML="大於0";}
						else{
							document.getElementById("finalanswer").innerHTML="小於0";}
					}
					else{
						if(document.getElementById("lmcselect").value="0"){
							document.getElementById("finalanswer").innerHTML="大於0";}
						else if(document.getElementById("lmcselect").value="大於0"){
							document.getElementById("finalanswer").innerHTML="大於0";}
						else{
							if(document.getElementById("ymrtext").value>102912){
								document.getElementById("finalanswer").innerHTML="大於0";}
							else{
								if(document.getElementById("yctext").value>974048){
									document.getElementById("finalanswer").innerHTML="小於0";}
								else{
									if(document.getElementById("mctext").value>602544){
										document.getElementById("finalanswer").innerHTML="大於0";}
									else{
										if(document.getElementById("ymrtext").value>39774){
											document.getElementById("finalanswer").innerHTML="小於0";}
										else{
											document.getElementById("finalanswer").innerHTML="大於0";}
									}
								}
							}
						}
					}
				}
			}
		}
	}
$.ajax({
	type:"POST",
	url:"php/saverecord.php",
	data:{
		"codetext":document.getElementById("codetext").value,
		"mrtext":document.getElementById("mrtext").value,
		"lmrtext":document.getElementById("lmrtext").value,
		"ymrtext":document.getElementById("ymrtext").value,
		"mctext":document.getElementById("mctext").value,
		"yctext":document.getElementById("yctext").value,
		"ymselect":document.getElementById("ymselect").value,
		"lmcselect":document.getElementById("lmcselect").value,
		"finalanswer":document.getElementById("finalanswer").innerHTML,
	},
	success:function(data){
		alert("第"+data+"資料記錄成功");
	},
	error:function(){
	alert("發生錯誤 狀態:"+jqXHR.readyState + "    "+jqXHR.status);}
});
	document.getElementById("codetext").value="";
	document.getElementById("mrtext").value="";
	document.getElementById("lmrtext").value="";
	document.getElementById("ymrtext").value="";
	document.getElementById("mctext").value="";
	document.getElementById("yctext").value="";
	document.getElementById("ymselect").value="";
	document.getElementById("lmcselect").value="";
}
window.onload=function(){
	document.getElementById("codetext").value="";
	document.getElementById("mrtext").value="";
	document.getElementById("lmrtext").value="";
	document.getElementById("ymrtext").value="";
	document.getElementById("mctext").value="";
	document.getElementById("yctext").value="";
	document.getElementById("ymselect").value="";
	document.getElementById("lmcselect").value="";
}